#!/usr/bin/env node
// Writes the shared header into each page's HTML, so it paints with the body.
//
// The bar used to exist only at runtime: a page shipped `<header
// data-site-header></header>` and lib/header.js filled it once three module
// files had been fetched and evaluated. The body is markup in the file and
// paints immediately; the header could not, so it arrived visibly late on every
// navigation between pages.
//
// Generating it keeps the single source of truth that the runtime build was
// there to provide. docs/lib/header-markup.js holds the template, this script
// stamps it into the HTML, and lib/header.js uses the same function as a
// fallback for a page that has not been generated. A renamed tool is still one
// edit, in one file.
//
// Idempotent: it replaces whatever is between the header tags, so running it
// twice writes the same thing. The generated block is not hand-editable — an
// edit inside it is overwritten on the next build, which is what the marker
// comment in the output says.
import fs from "node:fs";
import path from "node:path";
import { DOCS_DIR, ROOT } from "./utils.js";
import { headerBarHtml, HEADER_PAGES } from "../docs/lib/header-markup.js";

// Matches the mount point whether it is still empty or already filled.
const HEADER_RE = /(<header data-site-header>)([\s\S]*?)(<\/header>)/;

const NOTE =
  "\n      <!-- Generated by scripts/build-header.js from docs/lib/header-markup.js.\n" +
  "           Do not edit here; edit the template and rebuild. -->\n      ";

let written = 0;
let skipped = 0;

for (const [file, options] of Object.entries(HEADER_PAGES)) {
  const full = path.join(DOCS_DIR, file);
  if (!fs.existsSync(full)) {
    console.warn(`  ${file}: not found, skipped`);
    skipped++;
    continue;
  }

  const before = fs.readFileSync(full, "utf8");
  if (!HEADER_RE.test(before)) {
    // A page that opted out, or whose mount point was renamed. Saying so beats
    // silently leaving one page with a late header.
    console.warn(`  ${file}: no <header data-site-header> to fill, skipped`);
    skipped++;
    continue;
  }

  const bar = headerBarHtml(options);
  const after = before.replace(HEADER_RE, (_, open, __, close) => `${open}${NOTE}${bar}\n    ${close}`);

  if (after === before) {
    console.log(`  ${file}: already current`);
    continue;
  }
  fs.writeFileSync(full, after);
  console.log(`  ${file}: header written`);
  written++;
}

console.log(
  `Header written into ${written} page${written === 1 ? "" : "s"}` +
    (skipped ? ` (${skipped} skipped)` : "") +
    `.`
);

/* --- icon count ----------------------------------------------------------- */
// The catalogue's size is quoted in three places a reader sees before any code
// runs: the homepage stat, the gallery's search placeholder, and the package
// description npm puts on the listing page. All three were hand-typed once and
// all three went stale — the homepage said 8,470 against a catalogue of 9,032,
// and the package said 9,032 against one of 7,892.
//
// So none of them is hand-typed now. Each is written from docs/icons.json, which
// generate-index.js has already produced by the time this runs, which makes the
// figure in the file the figure the build actually emitted. Removing or adding
// artwork needs no edit here or anywhere else: rebuild and every quoted total
// moves with it.
//
// Adding a fourth place means one more entry in TARGETS below. Each pattern has
// to capture the text either side of the digits, so the replacement can put the
// new number back between them.
//
// A page's figure can still differ from what /api/icons reports, by the number of
// icons an admin has hidden. That difference is live and belongs to the running
// site; the page replaces the build's figure with the server's as soon as it
// answers, which is why both exist.
const TARGETS = [
  { file: path.join(DOCS_DIR, "index.html"), re: /(<b\b[^>]*\bdata-icon-count\b[^>]*>)[\d,]*(<\/b>)/g },
  { file: path.join(DOCS_DIR, "gallery.html"), re: /(placeholder="Search icon from list of )[^"]*( icons \.\.\.")/ },
  // Raw text rather than parse-and-stringify, so the file keeps its own
  // formatting and key order instead of being rewritten by JSON.stringify.
  { file: path.join(ROOT, "package.json"), re: /("description": "[^"]*?library of )[\d,]*( icons)/ },
];

let total = null;
try {
  total = JSON.parse(fs.readFileSync(path.join(DOCS_DIR, "icons.json"), "utf8")).total;
} catch {
  console.warn("  icon count: docs/icons.json not readable, skipped");
}

if (typeof total === "number") {
  // Grouped, matching the figure the gallery writes over it once the API
  // answers. A bare 9031 replaced by 9,031 a moment later is the flicker that
  // writing the count into the file exists to remove.
  const shown = total.toLocaleString("en-US");
  for (const { file, re } of TARGETS) {
    if (!fs.existsSync(file)) continue;
    const before = fs.readFileSync(file, "utf8");
    const after = before.replace(re, `$1${shown}$2`);
    if (after === before) continue;
    fs.writeFileSync(file, after);
    console.log(`  ${path.basename(file)}: icon count set to ${shown}`);
  }
}
