#!/usr/bin/env node
// Writes the shared header into each page's HTML, so it paints with the body.
//
// The bar used to exist only at runtime: a page shipped `<header
// data-site-header></header>` and lib/header.js filled it once three module
// files had been fetched and evaluated. The body is markup in the file and
// paints immediately; the header could not, so it arrived visibly late on every
// navigation between pages.
//
// Generating it keeps the single source of truth that the runtime build was
// there to provide. docs/lib/header-markup.js holds the template, this script
// stamps it into the HTML, and lib/header.js uses the same function as a
// fallback for a page that has not been generated. A renamed tool is still one
// edit, in one file.
//
// Idempotent: it replaces whatever is between the header tags, so running it
// twice writes the same thing. The generated block is not hand-editable — an
// edit inside it is overwritten on the next build, which is what the marker
// comment in the output says.
import fs from "node:fs";
import path from "node:path";
import { DOCS_DIR } from "./utils.js";
import { headerBarHtml, HEADER_PAGES } from "../docs/lib/header-markup.js";

// Matches the mount point whether it is still empty or already filled.
const HEADER_RE = /(<header data-site-header>)([\s\S]*?)(<\/header>)/;

const NOTE =
  "\n      <!-- Generated by scripts/build-header.js from docs/lib/header-markup.js.\n" +
  "           Do not edit here; edit the template and rebuild. -->\n      ";

let written = 0;
let skipped = 0;

for (const [file, options] of Object.entries(HEADER_PAGES)) {
  const full = path.join(DOCS_DIR, file);
  if (!fs.existsSync(full)) {
    console.warn(`  ${file}: not found, skipped`);
    skipped++;
    continue;
  }

  const before = fs.readFileSync(full, "utf8");
  if (!HEADER_RE.test(before)) {
    // A page that opted out, or whose mount point was renamed. Saying so beats
    // silently leaving one page with a late header.
    console.warn(`  ${file}: no <header data-site-header> to fill, skipped`);
    skipped++;
    continue;
  }

  const bar = headerBarHtml(options);
  const after = before.replace(HEADER_RE, (_, open, __, close) => `${open}${NOTE}${bar}\n    ${close}`);

  if (after === before) {
    console.log(`  ${file}: already current`);
    continue;
  }
  fs.writeFileSync(full, after);
  console.log(`  ${file}: header written`);
  written++;
}

console.log(
  `Header written into ${written} page${written === 1 ? "" : "s"}` +
    (skipped ? ` (${skipped} skipped)` : "") +
    `.`
);

/* --- icon count ----------------------------------------------------------- */
// The catalogue's size appears in the markup twice: the homepage stat and the
// gallery's search placeholder. Both paint before any request answers, so both
// have to be in the file, and both were hand-typed and had gone stale — the
// homepage said 8,470 against a catalogue of 9,032.
//
// Written from docs/icons.json, which generate-index.js has already produced by
// the time this runs, so the figure in the file is the figure the build emitted.
//
// It can still differ from what /api/icons reports, by the number of icons an
// admin has hidden. That difference is live and belongs to the running site;
// the page replaces the figure with the server's as soon as it answers.
const COUNT_RE = /(<b\b[^>]*\bdata-icon-count\b[^>]*>)[\d,]*(<\/b>)/g;
const PLACEHOLDER_RE = /(placeholder="Search icon from list of )[^"]*( icons \.\.\.")/;

let total = null;
try {
  total = JSON.parse(fs.readFileSync(path.join(DOCS_DIR, "icons.json"), "utf8")).total;
} catch {
  console.warn("  icon count: docs/icons.json not readable, skipped");
}

if (typeof total === "number") {
  const shown = total.toLocaleString("en-US");
  for (const file of ["index.html", "gallery.html"]) {
    const full = path.join(DOCS_DIR, file);
    if (!fs.existsSync(full)) continue;
    const before = fs.readFileSync(full, "utf8");
    const after = before
      .replace(COUNT_RE, `$1${shown}$2`)
      // Grouped, like the figure syncSearchPlaceholder writes over it once the
      // API answers. A bare 9031 here is replaced by 9,031 a moment later,
      // which is the flicker writing the count into the file exists to remove.
      .replace(PLACEHOLDER_RE, `$1${shown}$2`);
    if (after === before) continue;
    fs.writeFileSync(full, after);
    console.log(`  ${file}: icon count set to ${shown}`);
  }
}
