#!/usr/bin/env node
// Step 3 of the pipeline: from the manifest written by generate-components,
// emit ./src/index.ts (named re-exports + generateMetadata) and the
// ./docs/icons.json the preview page consumes.
import fs from "node:fs";
import path from "node:path";
import {
  SRC_DIR,
  DOCS_DIR,
  RAW_SVGS_DIR,
  MANIFEST_PATH,
  WEIGHTS,
  extractSvgInner,
  centerlinePaths,
} from "./utils.js";

if (!fs.existsSync(MANIFEST_PATH)) {
  console.error(
    `Error: ${MANIFEST_PATH} not found. Run generate-components.js first.`
  );
  process.exit(1);
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));

// --- src/index.ts ---------------------------------------------------------
const exportLines = manifest
  .map((m) => `export { ${m.component} } from "./icons/${m.component}";`)
  .join("\n");

const nameList = manifest
  .map((m) => `  "${m.component}",`)
  .join("\n");

const indexSource = `// AUTO-GENERATED by scripts/generate-index.js — do not edit by hand.
// Re-run \`npm run build:icons\` to regenerate.

export type { IconProps, IconWeight, IconLibraryMetadata } from "./types";
export { ICON_WEIGHTS } from "./types";
export { StrokeIcon } from "./StrokeIcon";
export type { StrokeIconProps } from "./StrokeIcon";
// Runtime name lookup. Fill the registry with the icons you use; see src/Icon.tsx
// for why it is not pre-filled with all of them.
export { Icon, registerIcons, isIconRegistered, registeredIcons } from "./Icon";
export type { IconComponent, NamedIconProps } from "./Icon";

${exportLines}

import { ICON_WEIGHTS } from "./types";
import type { IconLibraryMetadata } from "./types";

const ICON_NAMES = [
${nameList}
] as const;

// Returns the total icon count and the weights every icon supports.
export function generateMetadata(): IconLibraryMetadata {
  return {
    totalIcons: ICON_NAMES.length,
    weights: ICON_WEIGHTS,
    iconNames: [...ICON_NAMES],
  };
}
`;

fs.writeFileSync(path.join(SRC_DIR, "index.ts"), indexSource);

// --- docs/icons.json ------------------------------------------------------
// Enrich each entry with every weight's inner markup so the preview page can
// render real icons inline AND switch weights without fetching files (works
// over file://). Larger than regular-only, but it is a docs artifact only.
fs.mkdirSync(DOCS_DIR, { recursive: true });

/**
 * Which set drew an icon, from the source.json beside its artwork.
 *
 * The name carries a two-letter set code when another set already held the bare
 * name, but the code cannot be parsed off the end of it: `log-in`, `zoom-in`,
 * `arrows-in` and `water-ph` all end in something that looks like one and none
 * of them is. Only the recorded `base` says where the name stops.
 */
function provenance(dir) {
  try {
    const meta = JSON.parse(fs.readFileSync(path.join(dir, "source.json"), "utf8"));
    if (!meta.source) return {};
    if (meta.set) setNames[meta.source] = meta.set;
    return { source: meta.source, base: meta.base ?? undefined };
  } catch {
    return {};
  }
}

/**
 * Set code to display name, filled in as the artwork is read.
 *
 * The catalogue carries the code per icon and the names once here, rather than
 * the name on all 8,468 of them. Built from the artwork itself, so a set added
 * later needs no edit here and a name cannot drift from what the source.json
 * beside the drawing says.
 */
const setNames = {};

const icons = manifest.map((m) => {
  const dir = path.join(RAW_SVGS_DIR, m.name);
  const from = provenance(dir);

  // Stroke-based (AI) icon: derive all six weights from its centerline paths so
  // the gallery renders them, same as StrokeIcon does at runtime.
  let centerline = null;
  try {
    centerline = centerlinePaths(dir, m.name);
  } catch {
    // malformed centerline -> fall through to the per-weight reader (empties)
  }
  if (centerline) {
    // No `weights` here on purpose. They are a pure function of `centerline`, and
    // writing both put 12 MB of derived markup in a 26 MB file to save 1 MB of
    // source. readSeed() derives them on load instead.
    return {
      name: m.name,
      component: m.component,
      kind: "stroke",
      centerline,
      ...from,
    };
  }

  const weights = {};
  for (const weight of WEIGHTS) {
    const file = path.join(dir, `${m.name}-${weight}.svg`);
    try {
      weights[weight] = extractSvgInner(fs.readFileSync(file, "utf8"));
    } catch {
      weights[weight] = "";
    }
  }
  // A weight with no file resolves to regular here rather than being served as
  // an empty string, so the payload matches what the components render. This is
  // what gives a drawn icon its `sharp`: Phosphor ships no sharp artwork, and a
  // filled outline cannot have its corners un-rounded after the fact.
  for (const weight of WEIGHTS) {
    if (!weights[weight]) weights[weight] = weights.regular;
  }
  return { name: m.name, component: m.component, weights, ...from };
});
const docsData = {
  total: manifest.length,
  weights: WEIGHTS,
  sets: Object.fromEntries(Object.entries(setNames).sort(([a], [b]) => a.localeCompare(b))),
  icons,
};
fs.writeFileSync(
  path.join(DOCS_DIR, "icons.json"),
  JSON.stringify(docsData, null, 2) + "\n"
);

console.log(
  `Generated src/index.ts (${manifest.length} exports) and docs/icons.json.`
);
